### ISSUE TITLE
Interface Browser - error

### ISSUE THREAD

**Issue by vmburd** [DanDiplo/Umbraco.GodMode#1]
Hi Dan,

First thanks for this package. It's a god send :) 

I receive the following error whenever I try to view the Interface Browser page:

```
An error occured

The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; charset=utf-8'.

EXCEPTION DETAILS

System.InvalidOperationException: The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; charset=utf-8'.
STACKTRACE

INNER EXCEPTION

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Diplo.GodMode.Controllers.GodModeApiController.<GetAssembliesWithInterfaces>b__15(Assembly a)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)
   at System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()

```

The Assembly dropdown is empty.

Regards

Ver

**Comment by DanDiplo** [comment]
Hi Ver. Thanks for taking the time to log this. It looks like there is an issue with Reflection being able to access one or more of the assemblies in the /bin folder of your site. There seems like there can be a lot of different reasons for this, so hard to pinpoint an exact reason (unless you happen to be able to inspect the value of the LoaderExceptions property the Inner Exception references?).

There is some advise on SO for different ways this could be mitigated:
http://stackoverflow.com/questions/1091853/error-message-unable-to-load-one-or-more-of-the-requested-types-retrieve-the-l

I'll look at adding better exception catching and logging to try and at least avoid this error in the next release. But ultimately it's probably something related to permissions on your local version as this hasn't caused issues on the sites I've tested it on.

**Comment by vmburd** [comment]
I'll see if I can debug this tomorrow. The site is still in development and being run on my PC.

**Comment by DanDiplo** [comment]
@vmburd I know it's been a long time, but I found a site that I could replicate this error in and believe I've now fixed it. If you grab the latest package (from Our or NuGet) it should be fixed.

**Comment by vmburd** [comment]
Hi @DanDiplo,

I just tried this and the new package works.  

Thanks :)
