### ISSUE TITLE
ServerRole.. checking isMaster when it should now be isSchedulingPublisher?

### ISSUE THREAD

**Issue by mistyn8** [DanDiplo/Umbraco.GodMode#29]
Seeing some log errors when checking serverRole for GM>Diagnotics/ServerConfiguration..
I think this is down to v9 updating a column name.. `isMaster became isSchedulingPublisher`

https://github.com/DanDiplo/Umbraco.GodMode/blob/dc2e17c383756dece228013308e000a93fafd4f4/Diplo.GodMode/Services/UmbracoDatabaseService.cs#L318

https://github.com/umbraco/Umbraco-CMS/blob/v9/9.5/src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_0_0/UmbracoServerColumn.cs#L17

```
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'IsMaster'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 236
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.Database.Fetch[T](Sql sql)
   at NPoco.Database.Fetch[T](String sql, Object[] args)
   at Diplo.GodMode.Services.UmbracoDatabaseService.GetRegistredServers()
   at Diplo.GodMode.Services.DiagnosticService.GetDiagnosticGroups()
ClientConnectionId:7b9eaeb7-d136-440a-9e42-5d1bb32650b2
Error Number:207,State:1,Class:16
ClientConnectionId before routing:6a4a80ab-b063-437c-b02f-b625692af139
Routing Destination:ca40a9f3d364.tr5040.uksouth1-a.worker.database.windows.net,11023
```

**Comment by DanDiplo** [comment]
Good spot! I'll update for the next release!

**Comment by mistyn8** [comment]
If I get a chance I'll try and sort a pr :-)

**Comment by DanDiplo** [comment]
Hi Mike. I've released a new version that should fix this issue - https://www.nuget.org/packages/Diplo.GodMode/9.2.2 Thanks once again for your help!
